version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - LOCAL_S3_DIR=/app/local-s3-bucket
    volumes:
      - shared-storage:/app/local-s3-bucket
    depends_on:
      - redis

  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    environment:
      - REDIS_URL=redis://redis:6379
      - LOCAL_S3_DIR=/app/local-s3-bucket
      - BASE_URL=http://localhost:4000
      - PUBLIC_BASE_URL=http://localhost:3001
    volumes:
      - shared-storage:/app/local-s3-bucket
    depends_on:
      - redis

  request-handler:
    build:
      context: .
      dockerfile: Dockerfile.request-handler
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - LOCAL_S3_DIR=/app/local-s3-bucket
    volumes:
      - shared-storage:/app/local-s3-bucket

volumes:
  redis_data:
  shared-storage:
