FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* turbo.json ./
COPY packages/ ./packages/
COPY apps/request-handler/ ./apps/request-handler/

RUN npm install --legacy-peer-deps

RUN mkdir -p /app/local-s3-bucket

ENV LOCAL_S3_DIR=/app/local-s3-bucket

CMD ["npx", "ts-node", "apps/request-handler/src/index.ts"]
