services:
  - type: redis
    name: dockyard-redis
    plan: free
    ipAllowList: []

  - type: web
    name: dockyard-web
    env: docker
    dockerfilePath: Dockerfile.web
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: dockyard-redis
          property: connectionString

  - type: web
    name: dockyard-builder
    env: docker
    dockerfilePath: Dockerfile.builder
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: dockyard-redis
          property: connectionString
      - key: BASE_URL
        fromService:
          type: web
          name: dockyard-request-handler
          property: host
      - key: PUBLIC_BASE_URL
        fromService:
          type: web
          name: dockyard-web
          property: host

  - type: web
    name: dockyard-request-handler
    env: docker
    dockerfilePath: Dockerfile.request-handler
    plan: free
